(() => {
  const getElements = () => ({
    pickProjectBtn: document.getElementById("pick-project"),
    loadSidecarBtn: document.getElementById("load-sidecar"),
    pickPhotosBtn: document.getElementById("pick-photos"),
    rescanPhotosBtn: document.getElementById("rescan-photos-run"),
    saveSidecarBtn: document.getElementById("save-sidecar"),
    saveLogBtn: document.getElementById("save-log"),
    openSettingsBtn: document.getElementById("open-settings"),
    importModal: document.getElementById("import-modal"),
    importCloseBtn: document.getElementById("import-close-btn"),
    importBackdrop: document.getElementById("import-close"),
    importActionBtn: document.getElementById("import-photos-run"),
    exportActionBtn: document.getElementById("export-photos-run"),
    settingsModal: document.getElementById("settings-modal"),
    settingsCloseBtn: document.getElementById("settings-close-btn"),
    settingsBackdrop: document.getElementById("settings-close"),
    firstRunModal: document.getElementById("first-run-modal"),
    firstRunPickBtn: document.getElementById("first-run-pick"),
    libraryModal: document.getElementById("library-modal"),
    libraryListEl: document.getElementById("library-list"),
    obsTagInput: document.getElementById("obs-tag-input"),
    obsTagAddBtn: document.getElementById("obs-tag-add"),
    obsTagList: document.getElementById("obs-tag-list"),
    statusEl: document.getElementById("status"),
    statusTextEl: document.getElementById("status-text"),
    statusCloseBtn: document.getElementById("status-close"),
    photoMetaEl: document.getElementById("photo-meta"),
    photoImageEl: document.getElementById("photo-image"),
    photoFilenameEl: document.getElementById("photo-filename"),
    photoUnsortedBtn: document.getElementById("photo-unsorted"),
    photoClearFiltersBtn: document.getElementById("photo-clear-filters"),
    filterToggleBtn: document.getElementById("filter-toggle"),
    countToggleBtn: document.getElementById("count-toggle"),
    prevBtn: document.getElementById("prev-photo"),
    nextBtn: document.getElementById("next-photo"),
    notesEl: document.getElementById("photo-notes"),
    layoutEl: document.querySelector(".layout"),
    layoutSplitterEl: document.getElementById("layout-splitter"),
    panels: {
      report: document.getElementById("panel-report"),
      observations: document.getElementById("panel-observations"),
      training: document.getElementById("panel-training"),
    },
  });

  window.AutoBerichtPhotoSorterElements = { getElements };
})();
