// Auto-generated by tools/extract_pscategorylabels.js
window.PS_CATEGORY_LABELS_META = {
  "sourceWorkbook": "2025-07-10 AutoBericht v0 Berichtform report selectors.xlsx",
  "sheet": "PSCategoryLabels",
  "generatedAt": "2026-01-05T15:01:47.388Z"
};
window.PS_CATEGORY_LABELS_SEED = {
  "report": [
    {
      "value": "1",
      "label": "1 Leitbild, Sicherheitsziele und Strategien"
    },
    {
      "value": "1.1",
      "label": "1.1. Unternehmensleitbild, Führungsgrundsätze"
    },
    {
      "value": "8.1",
      "label": "8.1. Mitwirkung der Mitarbeitenden"
    },
    {
      "value": "1.2",
      "label": "1.2. Engagement der Geschäftsleitung"
    },
    {
      "value": "9.2",
      "label": "9.2. Arbeitsbelastung, Arbeitszufriedenheit"
    },
    {
      "value": "1.3",
      "label": "1.3. Engagement der Linienvorgesetzten"
    },
    {
      "value": "1.4",
      "label": "1.4. Sicherheitsziele"
    },
    {
      "value": "1.5",
      "label": "1.5. Zielbildung, Controlling und Strategie"
    },
    {
      "value": "2",
      "label": "2. Organisation"
    },
    {
      "value": "2.1",
      "label": "2.1. Betriebsorganisation"
    },
    {
      "value": "2.2",
      "label": "2.2 Sicherheitsorganisation"
    },
    {
      "value": "2.3",
      "label": "2.3. Relevante Grundlagen"
    },
    {
      "value": "3",
      "label": "3. Befähigung, Schulung, Kommunikation"
    },
    {
      "value": "3.1",
      "label": "3.1. Auswahlkriterien, Arbeitsverträge"
    },
    {
      "value": "3.2",
      "label": "3.2. Neueintretende Mitarbeitende"
    },
    {
      "value": "3.3",
      "label": "3.3. Schulungsbedürfnisse, Personalförderung"
    },
    {
      "value": "3.4",
      "label": "3.4. Personalschulung"
    },
    {
      "value": "3.5",
      "label": "3.5. Ausbildung am Arbeitsplatz"
    },
    {
      "value": "3.6",
      "label": "3.6. Mitarbeiterbeurteilung"
    },
    {
      "value": "3.7",
      "label": "3.7. Informationskonzept"
    },
    {
      "value": "3.8",
      "label": "3.8. Kommunikation, Mittel und Anlässe"
    },
    {
      "value": "3.9",
      "label": "3.9.  Sicherheit als Traktandum"
    },
    {
      "value": "3.10",
      "label": "3.10. Anforderugen an Fremdfirmen"
    },
    {
      "value": "4",
      "label": "4. Sicherheitsstandards"
    },
    {
      "value": "4.1",
      "label": "4.1. Merkblätter, Weisungen und Checklisten"
    },
    {
      "value": "4.2",
      "label": "4.2. Persönlicher Schutz: Bedürfnisse"
    },
    {
      "value": "4.3",
      "label": "4.3. Persönlicher Schutz: Anwendung"
    },
    {
      "value": "4.4",
      "label": "4.4. Normalbetrieb / Sonderbetrieb"
    },
    {
      "value": "4.5",
      "label": "4.5. Instandhaltung von Arbeitsmitteln"
    },
    {
      "value": "4.6",
      "label": "4.6. Gebäude und Anlagen"
    },
    {
      "value": "4.7",
      "label": "4.7. Beschaffung von Arbeitsmitteln"
    },
    {
      "value": "4.8",
      "label": "4.8. Stichproben"
    },
    {
      "value": "5",
      "label": "5. Gefährdungsermittlung, Risikobeurteilung"
    },
    {
      "value": "5.1",
      "label": "5.1. Beizug (gemäss EKAS-Richtlinie 6508)"
    },
    {
      "value": "5.2",
      "label": "5.2. Gefährdungsermittlung"
    },
    {
      "value": "5.3",
      "label": "5.3. Risikobeurteilung"
    },
    {
      "value": "5.4",
      "label": "5.4. Ereignisanalyse"
    },
    {
      "value": "6",
      "label": "6. Massnahmen"
    },
    {
      "value": "6.1",
      "label": "6.1. Massnahmenfindung"
    },
    {
      "value": "6.2",
      "label": "6.2. Sicherheitsprogramme"
    },
    {
      "value": "7",
      "label": "7. Notfallorganisation"
    },
    {
      "value": "7.1",
      "label": "7.1. Notfallkonzept"
    },
    {
      "value": "7.2",
      "label": "7.2. Personelle Bedingungen"
    },
    {
      "value": "7.3",
      "label": "7.3. Brandschutz"
    },
    {
      "value": "8",
      "label": "8. Mitwirkung"
    },
    {
      "value": "9",
      "label": "9. Gesundheitsschutz"
    },
    {
      "value": "9.1",
      "label": "9.1. Arbeitsgestaltung"
    },
    {
      "value": "9.3",
      "label": "9.3. Physische Arbeitsbelastung"
    },
    {
      "value": "9.4",
      "label": "9.4. Psychische Arbeitsbelastung"
    },
    {
      "value": "9.5",
      "label": "9.5. Arbeitszeitregelung"
    },
    {
      "value": "9.6",
      "label": "9.6. Pausengestaltung"
    },
    {
      "value": "9.7",
      "label": "9.7. Entlöhnungsform"
    },
    {
      "value": "9.8",
      "label": "9.8. Gesundheitsgefährdende Stoffe"
    },
    {
      "value": "9.9",
      "label": "9.9. Risikoverhalten, Suchtmittel, Krankheit"
    },
    {
      "value": "9.10",
      "label": "9.10. Gestaltung von Arbeitsplätzen und Betriebsmitteln"
    },
    {
      "value": "10",
      "label": "10. Kontrolle"
    },
    {
      "value": "10.1",
      "label": "10.1. Sicherheitsaudits"
    },
    {
      "value": "10.2",
      "label": "10.2. Ereignisstatistik"
    },
    {
      "value": "10.3",
      "label": "10.3. Fluktuation"
    },
    {
      "value": "11",
      "label": "11. Absenzenmanagement"
    },
    {
      "value": "12",
      "label": "12 Freizeitsicherheit (Fakultativ)"
    },
    {
      "value": "13",
      "label": "13 BGM (Fakultativ)"
    },
    {
      "value": "14",
      "label": "14 Erweiterung für ISO 45001 (Fakultativ)"
    }
  ],
  "training": [
    {
      "value": "Audit",
      "label": "Audit"
    },
    {
      "value": "Gefährdungsermittlung",
      "label": "Gefährdungsermittlung"
    },
    {
      "value": "Handeln, Dulden, Unterlassen",
      "label": "Handeln, Dulden, Unterlassen"
    },
    {
      "value": "Kommunikation",
      "label": "Kommunikation"
    },
    {
      "value": "Massnahmen TOP",
      "label": "Massnahmen TOP"
    },
    {
      "value": "Notfallorganisation",
      "label": "Notfallorganisation"
    },
    {
      "value": "StGB Art. 230",
      "label": "StGB Art. 230"
    },
    {
      "value": "Eisberg",
      "label": "Eisberg"
    },
    {
      "value": "Vorbild",
      "label": "Vorbild"
    }
  ],
  "observations": [
    {
      "value": "Unsorted",
      "label": "Unsorted"
    },
    {
      "value": "Stapler",
      "label": "Stapler"
    },
    {
      "value": "Leitern",
      "label": "Leitern"
    },
    {
      "value": "Elektro",
      "label": "Elektro"
    },
    {
      "value": "Palettenrolli",
      "label": "Palettenrolli"
    }
  ]
};
