(() => {
  const getElements = () => ({
    pickFolderBtn: document.getElementById("pick-folder"),
    loadSidecarBtn: document.getElementById("load-sidecar"),
    saveSidecarBtn: document.getElementById("save-sidecar"),
    importSelfBtn: document.getElementById("import-self"),
    loadSeedsBtn: document.getElementById("load-seeds"),
    saveLogBtn: document.getElementById("save-log"),
    openSpiderBtn: document.getElementById("open-spider"),
    openSettingsBtn: document.getElementById("open-settings"),
    settingsModal: document.getElementById("settings-modal"),
    settingsBackdrop: document.getElementById("settings-close"),
    closeSettingsBtn: document.getElementById("close-settings"),
    saveSettingsBtn: document.getElementById("save-settings"),
    generateLibraryBtn: document.getElementById("generate-library"),
    settingsAuthorEl: document.getElementById("settings-author"),
    settingsInitialsEl: document.getElementById("settings-initials"),
    settingsCompanyEl: document.getElementById("settings-company"),
    settingsCompanyIdEl: document.getElementById("settings-companyid"),
    settingsLocaleEl: document.getElementById("settings-locale"),
    settingsLibraryHintEl: document.getElementById("settings-library-hint"),
    statusEl: document.getElementById("status"),
    chapterListEl: document.getElementById("chapter-list"),
    chapterTitleEl: document.getElementById("chapter-title"),
    rowsEl: document.getElementById("rows"),
    photoOverlayEl: document.getElementById("photo-overlay"),
    photoOverlayClose: document.getElementById("photo-overlay-close"),
    photoOverlayCloseBtn: document.getElementById("photo-overlay-close-btn"),
    photoOverlayPrevBtn: document.getElementById("photo-overlay-prev"),
    photoOverlayNextBtn: document.getElementById("photo-overlay-next"),
    photoOverlayTitle: document.getElementById("photo-overlay-title"),
    photoOverlayImage: document.getElementById("photo-overlay-image"),
    checklistOverlayEl: document.getElementById("checklist-overlay"),
    checklistOverlayClose: document.getElementById("checklist-overlay-close"),
    checklistOverlayCloseBtn: document.getElementById("checklist-overlay-close-btn"),
    checklistOverlayTitle: document.getElementById("checklist-overlay-title"),
    checklistOverlayHint: document.getElementById("checklist-overlay-hint"),
    checklistFiltersEl: document.getElementById("checklist-filters"),
    checklistListEl: document.getElementById("checklist-list"),
    spiderModal: document.getElementById("spider-modal"),
    spiderCloseBtn: document.getElementById("spider-close-btn"),
    spiderCancelBtn: document.getElementById("spider-cancel"),
    spiderBackdrop: document.getElementById("spider-close"),
    spiderSaveBtn: document.getElementById("spider-save"),
    spiderTableBody: document.getElementById("spider-table-body"),
    filterModeEls: Array.from(document.querySelectorAll('input[name="filter-mode"]')),
  });

  window.AutoBerichtElements = { getElements };
})();
