(() => {
  const getElements = () => ({
    pickFolderBtn: document.getElementById("pick-folder"),
    loadSidecarBtn: document.getElementById("load-sidecar"),
    saveSidecarBtn: document.getElementById("save-sidecar"),
    importSelfBtn: document.getElementById("import-self"),
    loadSeedsBtn: document.getElementById("load-seeds"),
    saveLogBtn: document.getElementById("save-log"),
    openSpiderBtn: document.getElementById("open-spider"),
    openSettingsBtn: document.getElementById("open-settings"),
    settingsModal: document.getElementById("settings-modal"),
    settingsBackdrop: document.getElementById("settings-close"),
    closeSettingsBtn: document.getElementById("close-settings"),
    saveSettingsBtn: document.getElementById("save-settings"),
    generateLibraryBtn: document.getElementById("generate-library"),
    settingsModeratorEl: document.getElementById("settings-moderator"),
    settingsModeratorInitialsEl: document.getElementById("settings-moderator-initials"),
    settingsCoModeratorEl: document.getElementById("settings-co-moderator"),
    settingsCoInitialsEl: document.getElementById("settings-co-initials"),
    settingsCompanyEl: document.getElementById("settings-company"),
    settingsCompanyIdEl: document.getElementById("settings-companyid"),
    settingsLocaleEl: document.getElementById("settings-locale"),
    settingsBackupMinutesEl: document.getElementById("settings-backup-minutes"),
    settingsLibraryHintEl: document.getElementById("settings-library-hint"),
    statusEl: document.getElementById("status"),
    chapterListEl: document.getElementById("chapter-list"),
    chapterTitleEl: document.getElementById("chapter-title"),
    rowsEl: document.getElementById("rows"),
    photoOverlayEl: document.getElementById("photo-overlay"),
    photoOverlayClose: document.getElementById("photo-overlay-close"),
    photoOverlayCloseBtn: document.getElementById("photo-overlay-close-btn"),
    photoOverlayPrevBtn: document.getElementById("photo-overlay-prev"),
    photoOverlayNextBtn: document.getElementById("photo-overlay-next"),
    photoOverlayTitle: document.getElementById("photo-overlay-title"),
    photoOverlayImage: document.getElementById("photo-overlay-image"),
    checklistOverlayEl: document.getElementById("checklist-overlay"),
    checklistOverlayClose: document.getElementById("checklist-overlay-close"),
    checklistOverlayCloseBtn: document.getElementById("checklist-overlay-close-btn"),
    checklistOverlayTitle: document.getElementById("checklist-overlay-title"),
    checklistOverlayHint: document.getElementById("checklist-overlay-hint"),
    checklistFiltersEl: document.getElementById("checklist-filters"),
    checklistListEl: document.getElementById("checklist-list"),
    checklistSearchEl: document.getElementById("checklist-search"),
    firstRunModal: document.getElementById("first-run-modal"),
    firstRunPickBtn: document.getElementById("first-run-pick"),
    libraryModal: document.getElementById("library-modal"),
    libraryListEl: document.getElementById("library-list"),
    spiderModal: document.getElementById("spider-modal"),
    spiderCloseBtn: document.getElementById("spider-close-btn"),
    spiderCancelBtn: document.getElementById("spider-cancel"),
    spiderBackdrop: document.getElementById("spider-close"),
    spiderSaveBtn: document.getElementById("spider-save"),
    spiderTableBody: document.getElementById("spider-table-body"),
    chapterPreviewModal: document.getElementById("chapter-preview-modal"),
    chapterPreviewBackdrop: document.getElementById("chapter-preview-close"),
    chapterPreviewCloseBtn: document.getElementById("chapter-preview-close-btn"),
    chapterPreviewTitle: document.getElementById("chapter-preview-title"),
    chapterPreviewBody: document.getElementById("chapter-preview-body"),
    filterAnswerModeEls: Array.from(document.querySelectorAll('input[name="filter-answer-mode"]')),
    filterIncludeModeEls: Array.from(document.querySelectorAll('input[name="filter-include-mode"]')),
    filterDoneModeEls: Array.from(document.querySelectorAll('input[name="filter-done-mode"]')),
  });

  window.AutoBerichtElements = { getElements };
})();
