const fs = require("fs");
const path = require("path");
const XLSX = require("../AutoBericht/libs/sheetjs/xlsx.full.min.js");

const workbookPath = process.argv[2] || path.join("fromWork", "2025-07-10 AutoBericht v0 Berichtform report selectors.xlsx");
const outJson = process.argv[3] || path.join("data", "seed", "pscategorylabels.json");
const outJs = process.argv[4] || path.join("AutoBericht", "mini", "pscategorylabels.seed.js");

const readWorkbook = (filePath) => {
  const buffer = fs.readFileSync(filePath);
  return XLSX.read(buffer, { type: "buffer" });
};

const parsePSCategoryLabels = (rows) => {
  const reportLabels = [];
  const seminarLabels = [];
  const topicLabels = [];
  rows.forEach((row) => {
    const reportA = String(row[0] || "").trim();
    const seminar = String(row[1] || "").trim();
    const topic = String(row[2] || "").trim();
    const reportB = String(row[3] || "").trim();
    if (reportA) reportLabels.push(reportA);
    if (reportB) reportLabels.push(reportB);
    if (seminar) seminarLabels.push(seminar);
    if (topic) topicLabels.push(topic);
  });

  const reportOptions = reportLabels.map((label) => {
    const match = label.match(/^\d+(?:\.\d+)*(?:\.)?/);
    const value = match ? match[0].replace(/\.$/, "") : label;
    return { value, label };
  });

  const toUnique = (options) => {
    const seen = new Set();
    return options.filter((opt) => {
      if (!opt || !opt.value) return false;
      if (seen.has(opt.value)) return false;
      seen.add(opt.value);
      return true;
    });
  };

  return {
    bericht: toUnique(reportOptions),
    seminar: toUnique(seminarLabels.map((label) => ({ value: label, label }))),
    topic: toUnique(topicLabels.map((label) => ({ value: label, label }))),
  };
};

const workbook = readWorkbook(workbookPath);
const sheetName = workbook.SheetNames.find((name) => name.toLowerCase() === "pscategorylabels");
if (!sheetName) {
  throw new Error("Sheet PSCategoryLabels not found.");
}

const rows = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], { header: 1, blankrows: false });
const options = parsePSCategoryLabels(rows);

const payload = {
  meta: {
    sourceWorkbook: path.basename(workbookPath),
    sheet: sheetName,
    generatedAt: new Date().toISOString(),
  },
  options,
};

fs.mkdirSync(path.dirname(outJson), { recursive: true });
fs.writeFileSync(outJson, JSON.stringify(payload, null, 2) + "\n", "utf8");

const jsPayload = `// Auto-generated by tools/extract_pscategorylabels.js\n` +
  `window.PS_CATEGORY_LABELS_META = ${JSON.stringify(payload.meta, null, 2)};\n` +
  `window.PS_CATEGORY_LABELS_SEED = ${JSON.stringify(payload.options, null, 2)};\n`;

fs.writeFileSync(outJs, jsPayload, "utf8");

console.log(`Wrote ${outJson}`);
console.log(`Wrote ${outJs}`);
